service: PizzaApp

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  environment:
    REGION: ${self:provider.region}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
          Resource:
            Fn::GetAtt:
              - PendingOrderQueue
              - Arn

functions:
  hello:
    handler: handler.newOrder
    environment:
      PENDING_ORDERS_QUEUE: 
        Ref: PendingOrderQueue
    events:
      - httpApi:
          path: /order
          method: POST

  getOrder:
    handler: handler.getOrder
    events: 
      - httpApi: 
          path: /order/{orderId}
          method: GET

  preOrder:
    handler: handler.preOrder
    events: 
      - sqs: 
          arn: 
            Fn::GetAtt:
              - PendingOrderQueue
              - Arn
          batchSize: 1

resources:
  Resources:
    PendingOrderQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: PendingOrderQueue
