# nombre del proyecto o servicio.
service: PizzaApp

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: handler.newOrder
    events:
      - httpApi:
          path: /order
          method: POST
  getOrder:
    handler: handler.getOrder
    events: 
      - httpApi: 
          path: /order/{orderId}
          method: get
  preOrder:
    handler: handler.preOrder
    events: 
      - sqs: 
          arn: 
            Fn::GetAtt:
              - PendingOrderQueue
              - Arn
          batchSize: 1

resources:
  Resources:
    PendingOrderQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: PendingOrderQueue




